title: Vishnu's Ramblings
author: Vishnudev
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  From single-neuron activity arises our understanding of the world
  around us. But whether we can understand the single-neuron activiy
  arising from the world around us is still a question that is relevant
  today.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
